#!/usr/bin/env bash

source common-functions

chruby_auto() {
  [[ -s /usr/local/share/chruby/chruby.sh ]] && source /usr/local/share/chruby/chruby.sh
  [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

  chruby --version >/dev/null 2>&1
  if was_successful; then
    chruby $(cat .ruby-version)
  fi

  rbenv --version >/dev/null 2>&1
  if was_successful; then
    eval "$(rbenv init -)"
    rbenv local $(cat .ruby-version)
  fi

  rvm --version >/dev/null 2>&1
  if was_successful; then
    rvm use $(cat .ruby-version)
  fi
}
