#!/usr/bin/env bash

source common-functions

ensure_bundle() {
  which bundle >/dev/null 2>&1 || gem install bundler || (echo "installing bundle gem failed" && exit 1)
  bundle check >/dev/null || bundle install || exit 1
}

parallel_prepare() {
  bundle exec rake parallel:prepare >/dev/null || exit 1
}

bundle_exec_if_gemfile() {
  ls ./Gemfile >/dev/null 2> /dev/null
  if was_successful; then
    ensure_bundle
    bundle exec $*
  else
     $*
  fi
}

is_looking_like_a_ruby_project() {
  ls ./Gemfile >/dev/null 2> /dev/null
  if was_successful; then return 0; fi
  ls ./Rakefile >/dev/null 2> /dev/null
  if was_successful; then return 0; fi
  ls ./.ruby-version >/dev/null 2> /dev/null
  if was_successful; then return 0; fi
  return 1
}
