#!/usr/bin/env ruby

begin
  require 'listen'
rescue LoadError
  puts "run `gem install listen`"
  exit 1
end

dir = Dir.pwd

def run
  kill
  system "clear" or system "cls"
  system "printf '\e[3J'"
  system "reset"
  @running = Process.spawn("simple-rspec")
end

def kill
  return unless @running
  system("kill #{@running}")
  Process.wait
end

run

listener = Listen.to(dir) do |modified, added, removed|
  run
end

begin
  listener.start
  sleep
rescue Interrupt
  exit 130
end
