#!/usr/bin/env ruby

def find_and_replace_focus(path)
  text = File.read(path)

  replace = text

  replace = replace.gsub(/(^\s*(RSpec.describe|describe|context|it|scenario) .*)(,\s*focus:\s+true)( do\s*$)/, '\1\4')
  replace = replace.gsub(/(^\s*(RSpec.describe|describe|context|it|scenario) .*)(,\s*:focus\s*=>\s*true)( do\s*$)/, '\1\4')
  replace = replace.gsub(/(^\s*(RSpec.describe|describe|context|it|scenario) .*)(,\s*:focus)( do\s*$)/, '\1\4')

  if text != replace
    puts path
    File.open(path, 'w') { |file| file.puts replace }
  end
end

file_paths = Dir.glob('**/*').select { |path| File.file?(path) && path.end_with?('.rb') }

file_paths.each do |path|
  find_and_replace_focus(path)
end
