#!/usr/bin/env ruby

def find_and_replace(path, old, new)
  text = File.read(path)
  replace = text.gsub(old, new)
  if text != replace
    puts path
    File.open(path, 'w') { |file| file.puts replace }
  end
end

file_paths = Dir.glob('**/*').select { |path| File.file?(path) && path.end_with?('.rb') }

file_paths.each do |path|
  find_and_replace(path, /, focus: true/, '')
end
