#!/usr/bin/env bash

source common-functions

rm spec/_console.rb 2>/dev/null
cp $script_dir/rspec_console/templates/_console.rb ./spec/_console.rb
rspec spec/_console.rb
rm spec/_console.rb 2>/dev/null
