#!/usr/bin/env bash

script_dir=$( cd "$( dirname "$0" )" && pwd )
source $script_dir/common-functions

which update-gathering >/dev/null
if was_successful; then
  echo "Looks like gathering is already installed"
  exit 0
fi

echo "Detecting shell..."
cat /etc/shells | grep /bash >/dev/null
if was_successful; then
  echo ""
  echo "bash is installed"
  echo "- adding to ~/.bash_profile"
  echo "" >> ~/.bash_profile
  echo "source $script_dir/source-gathering-bash" >> ~/.bash_profile
fi

cat /etc/shells | grep /zsh >/dev/null
if was_successful; then
  echo ""
  echo "zsh is installed"
  echo "- adding to ~/.zshrc"
  echo "" >> ~/.zshrc
  echo "source $script_dir/source-gathering-zsh" >> ~/.zshrc
fi

cat /etc/shells | grep /fish >/dev/null
if was_successful; then
  echo ""
  echo "fish is installed"
  echo "- adding to ~/.config/fish/config.fish"
  echo "" >> ~/.config/fish/config.fish
  echo "source $script_dir/source-gathering-fish" >> ~/.config/fish/config.fish
fi

echo ""
echo "Complete! Restart your shell to use the scripts."
