#!/usr/bin/env ruby

stat = `netstat -vanp tcp | grep ::1.#{ARGV.first} | grep LISTEN`
result = stat.split(" ").last(2).first rescue
result or result = ""

if result.length > 0
  puts result
  exit 0
else
  exit 1
end
