#!/usr/bin/env bash

source common-functions
source common-ruby

if is_looking_like_a_ruby_project; then
  bundle show rspec >/dev/null
  if was_successful; then
    bundle_exec_if_gemfile rspec
  else
    bundle_exec_if_gemfile rake test
  fi

  exit $?
fi

# TODO: iOS
