#!/usr/bin/env bash

source common-functions

if [[ $1 != "--no-interaction" ]]; then
  check_sudo

  execute sudo mkdir -p /Library/Caches/Homebrew
  execute sudo chown -R `whoami` /Library/Caches/Homebrew
fi

execute git config --global credential.helper "osxkeychain"
execute git config --global push.default "current"

execute chmod 600 ~/.ssh/*
execute chmod 644 ~/.ssh/known_hosts

execute defaults -currentHost write com.apple.ImageCapture disableHotPlug -bool true

# Disable press-and-hold for keys in favor of key repeat
execute defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

# Set a blazingly fast keyboard repeat rate
execute defaults write NSGlobalDomain KeyRepeat -int 2
execute defaults write NSGlobalDomain InitialKeyRepeat -int 10

mkdir ~/Library/KeyBindings/ 2>/dev/null
rm ~/Library/KeyBindings/DefaultKeyBinding.dict 2>/dev/null
touch ~/Library/KeyBindings/DefaultKeyBinding.dict
echo '{
"~ " = ("insertText:", " ");
}' >> ~/Library/KeyBindings/DefaultKeyBinding.dict
check_last "Disable weird alt+space thing"

execute ssh-add -A

ls .bundle/config >/dev/null 2>&1
if was_successful; then
  warn ".bundle/config exists"
fi

ls ./*/xcuserdata/`whoami`.xcuserdatad/UserInterfaceState.xcuserstate >/dev/null 2>&1
if was_successful; then
  successfully rm ./*/xcuserdata/`whoami`.xcuserdatad/UserInterfaceState.xcuserstate
fi

ls ./*/*/xcuserdata/`whoami`.xcuserdatad/UserInterfaceState.xcuserstate >/dev/null 2>&1
if was_successful; then
  successfully rm ./*/*/xcuserdata/`whoami`.xcuserdatad/UserInterfaceState.xcuserstate
fi

execute touch ~/.hushlogin

echo "Current Wi-Fi: $(wifi)"

#TODO add this in:
# https://www.quernus.co.uk/2015/10/22/force-git-to-use-ssh/
