#!/usr/bin/env bash

source common-functions

check_sudo

execute sudo mkdir -p /usr/local
execute sudo mkdir -p /Library/Caches/Homebrew
execute sudo chown -R `whoami` /usr/local
execute sudo chown -R `whoami` /Library/Caches/Homebrew

execute git config --global credential.helper "osxkeychain"
execute git config --global push.default "current"

execute defaults -currentHost write com.apple.ImageCapture disableHotPlug -bool true
execute defaults write NSGlobalDomain KeyRepeat -int 0

execute brew update
execute brew doctor

execute wifi

ls .bundle/config >/dev/null 2>&1
if was_successful; then
  warn ".bundle/config exists"
fi


#TODO add this in:
# https://www.quernus.co.uk/2015/10/22/force-git-to-use-ssh/
