#!/usr/bin/env bash

ping_func(){
    results=$(ping -c 1 -t 1 google.co.uk >/dev/null 2>/dev/null)
    return $?
}

check_net() {
  ping_func
  if [[ $? > 0 ]]; then
    echo "internet doesn't seem ok"
    networksetup -setairportpower en0 off
    sleep 3
    networksetup -setairportpower en0 on
    sleep 15
    check_net
  else
    echo "internet connection is ok 👍"
  fi
}

while :
do
  check_net
  if [[ $1 != 'forever' ]]; then
    exit 0
  fi
  sleep 5
done

# ruby -e '
# require "pry"
# def list_of_wifi
#   list = `/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -s`
#   list = list.split("\n").map do |line|
#     match = line.match(/(.*) \w\w:\w\w:\w\w:/)
#     if match
#       match[1].strip
#     else
#       nil
#     end
#   end
#   list = list.compact.uniq
# end

# puts list_of_wifi
# '
