#!/bin/bash

docker system prune -a

# Stop all
docker kill $(docker ps -q) 2>/dev/null

# Delete all containers
docker rm $(docker ps -a -q) 2>/dev/null

# Delete all images
docker rmi $(docker images -q) --force 2>/dev/null

# Remove all volumes
docker volume ls -qf dangling=true | xargs docker volume rm

docker ps
