#!/usr/bin/env ruby

require "mechanize"

if ARGV.size != 3
  puts %q{Usage: ruby xcode.rb USERNAME PASSWORD VERSION}
  puts %q{Example: ruby xcode.rb myusername@apple.com 123456 7.1 }
  exit
end

username = ARGV[0]
password = ARGV[1]
version = ARGV[2]
target = "https://developer.apple.com/services-account/download?path=/Developer_Tools/Xcode_#{version}/Xcode_#{version}.dmg"

a = Mechanize.new { |agent|
  agent.user_agent_alias = 'Mac Safari'
}

a.get('https://developer.apple.com/') do |page|
  member_page = a.click(page.link_with(:text => /Member Center/))

  form = member_page.forms.first
  form.field_with(id: "accountname").value = username
  form.field_with(id: "accountpassword").value = password
  form.submit

  a.redirect_ok = false
  download_page = a.get(target)
  system %Q{ wget #{download_page.response["location"]} --header="Cookie: #{download_page.response["set-cookie"]}" }
end
