#!/usr/bin/env ruby

require "mechanize"
require_relative "../ruby/auth"

if ARGV.size != 1
  puts %q{Usage: download-xcode VERSION}
  puts %q{Example: download-xcode 7.1 }
  exit
end

login = Auth.new("developer.apple.com").find_or_create
username = login.account
password = login.password
version = ARGV[0]
target = "https://developer.apple.com/services-account/download?path=/Developer_Tools/Xcode_#{version}/Xcode_#{version}.dmg"

a = Mechanize.new { |agent|
  agent.user_agent_alias = 'Mac Safari'
}

a.get('https://developer.apple.com/') do |page|
  member_page = a.click(page.link_with(:text => /Account/))

  form = member_page.forms.first
  form.field_with(id: "accountname").value = username
  form.field_with(id: "accountpassword").value = password
  form.submit

  a.redirect_ok = false
  download_page = a.get(target)
  system %Q{ wget #{download_page.response["location"]} --header="Cookie: #{download_page.response["set-cookie"]}" }
end
