#!/usr/bin/env bash

source common-functions
source common-ruby

clean-derived-data || exit 1

ls ./Ambientfile >/dev/null 2> /dev/null
if was_successful; then
  retry 1 bundle_exec_if_gemfile ambient || exit 1
fi

ls ./Podfile >/dev/null 2> /dev/null
if was_successful; then
  retry 1 bundle_exec_if_gemfile pod install --no-repo-update || exit 1
fi

if [[ -d /Applications/Xcode.app/ ]]; then
  retry 1 open *.xcworkspace -a /Applications/Xcode.app
else
  retry 1 open *.xcworkspace
fi
