#!/usr/bin/env bash

source common-functions
source common-ruby

clean-derived-data || exit 1

ls ./Ambientfile >/dev/null 2> /dev/null
if was_successful; then
  retry 1 bundle_exec_if_gemfile ambient
fi

ls ./Podfile >/dev/null 2> /dev/null
if was_successful; then
  bundle_exec_if_gemfile pod check >/dev/null 2>&1 || retry 1 bundle_exec_if_gemfile pod install --no-repo-update
fi

ls ./Cartfile >/dev/null 2> /dev/null
if was_successful; then
  echo "There is a Cartfile. Be sure to run `carthage update`"
fi

if [[ -d /Applications/Xcode.app/ ]]; then
  retry 1 open *.xcworkspace -a /Applications/Xcode.app
else
  retry 1 open *.xcworkspace
fi
