#!/usr/bin/env bash

source common-functions
source common-ruby

ls ./*.podspec >/dev/null 2>&1 && ls ./Example >/dev/null 2>&1
if was_successful; then
  cd Example
  $script_dir/xcode
  exit $?
fi

ls ./Ambientfile >/dev/null 2> /dev/null
if was_successful; then
  retry 1 bundle_exec_if_gemfile ambient
fi

ls ./Podfile >/dev/null 2> /dev/null
if was_successful; then
  bundle_exec_if_gemfile pod check >/dev/null 2>&1 || retry 1 bundle_exec_if_gemfile pod install --no-repo-update
fi

ls ./Cartfile >/dev/null 2> /dev/null
if was_successful; then
  echo "There is a Cartfile. Be sure to run `carthage update`"
fi

xcode_path=$(ruby -e 'puts `xcode-select -p`.gsub("/Contents/Developer", "")')

xcworkspace() {
  ruby -e "exit system('cd $current_dir && open *.xcworkspace $*')"
}

xcodeproj() {
  ruby -e "exit system('cd $current_dir && open *.xcodeproj $*')"
}

open_project() {
  dont_care_if_executes xcworkspace $*
  if was_not_successful; then
    retry 1 xcodeproj $*
  fi
}

if [[ -d $xcode_path ]]; then
  open_project -a $xcode_path
else
  open_project
fi
