#!/usr/bin/env ruby

def default_branch
  branch = `basename $(git symbolic-ref refs/remotes/origin/HEAD)`.chomp
  branch = "master" if branch.nil?
  branch = "master" if branch == ""
  branch
end

target_branch = ARGV[0] || default_branch

url = `git config --get remote.origin.url`.strip
url.gsub!("git@", "https://")
url.gsub!(":", "/")
url.gsub!(".git", "")
url.gsub!("https///", "https://")
local_branch = `git rev-parse --abbrev-ref HEAD`
url = "#{url}/compare/#{target_branch}...#{local_branch}"

`open #{url}`
