#!/usr/bin/env ruby

url = `git config --get remote.origin.url`.strip
url.gsub!("git@", "https://")
url.gsub!(":", "/")
url.gsub!(".git", "")
url.gsub!("https///", "https://")
url = "#{url}/pulls"

url = "https://github.com/pulls" if url == "/pulls"

`open #{url}`
