#!/usr/bin/env ruby

# brew install rbenv/tap/openssl@1.0

files = Dir.glob(File.join(Dir.pwd, "**", ".ruby-version"))
versions = files
  .map { |path| File.read(path).chomp.split("ruby-").last }
  .uniq
  .map { |v| Gem::Version.new(v) }

log = ""

puts "installing versions: #{versions}"

versions.each do |version|
  if version < Gem::Version.new("2.4.0")
    system("ruby-install ruby #{version} -- --with-openssl-dir=$(brew --prefix openssl@1.0) --disable-install-doc") || begin
      log = log + "#{version} failed\n"
    end
  else
    system("ruby-install ruby #{version} --disable-install-doc") || begin
      log = log + "#{version} failed\n"
    end
  end
end

puts log
